### ISSUE TITLE
Start Error

### ISSUE THREAD

**Issue by RazerStvH** [GradientSurfer/Draw2Img#10]
When i try to start this thing, i have error:

`$ python3.10 -m venv ~/disks/ssh/my-venv draw2img/main.py`
`Error: Unable to create directory /home/Morselius/disks/ramdisk/Draw2Img/draw2img/main.py`

CPU: Intel(R) Core(TM) i5-8600K (6) @ 4,50 GHz
GPU: NVIDIA GeForce GTX 1070 Ti 8Gb
Ram: 32Gb
OS: Arch Linux
Python-3.10

All dependencies are installed and have the latest versions.

**Comment by RazerStvH** [comment]
Ok, with this error my mistake. Now i have started, but Draw2Img didnt do anything.
Maybe I didn't understand something, but I did everything according to the description

![Снимок экрана от 2024-08-04 21-55-59](https://github.com/user-attachments/assets/789f2dcf-c065-409a-9f5e-e329547da325)

**Comment by RazerStvH** [comment]
a little bit of logs

```
/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/models/transformers/transformer_2d.py:34: FutureWarning: `Transformer2DModelOutput` is deprecated and will be removed in version 1.0.0. Importing `Transformer2DModelOutput` from `diffusers.models.transformer_2d` is deprecated and this will be removed in a future version. Please use `from diffusers.models.modeling_outputs import Transformer2DModelOutput`, instead.
  deprecate("Transformer2DModelOutput", "1.0.0", deprecation_message)
Loading pipeline components...: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:04<00:00,  1.49it/s]
INFO:websocket_server:listening: ws://localhost:8079
INFO:draw2img:Web UI URL: http://localhost:8080
127.0.0.1 - - [04/Aug/2024 21:47:05] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [04/Aug/2024 21:47:05] "GET /assets/index-AQAbczng.js HTTP/1.1" 200 -
127.0.0.1 - - [04/Aug/2024 21:47:05] "GET /assets/index-6cmW4xtb.css HTTP/1.1" 200 -
127.0.0.1 - - [04/Aug/2024 21:47:05] "GET /apple-touch-icon.png HTTP/1.1" 200 -
127.0.0.1 - - [04/Aug/2024 21:47:05] "GET /favicon-16x16.png HTTP/1.1" 200 -
----------------------------------------
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 47016)
Exception occurred during processing of request from ('127.0.0.1', 47026)
Traceback (most recent call last):
  File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/Morselius/disks/ramdisk/Draw2Img/draw2img/main.py", line 34, in __init__
    super().__init__(*args, directory=dir, **kwargs)
  File "/usr/lib/python3.10/http/server.py", line 668, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/usr/lib/python3.10/http/server.py", line 675, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.10/http/server.py", line 875, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.10/shutil.py", line 198, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
Traceback (most recent call last):
BrokenPipeError: [Errno 32] Broken pipe
  File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/home/Morselius/disks/ramdisk/Draw2Img/draw2img/main.py", line 34, in __init__
    super().__init__(*args, directory=dir, **kwargs)
  File "/usr/lib/python3.10/http/server.py", line 668, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/usr/lib/python3.10/http/server.py", line 675, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/lib/python3.10/http/server.py", line 875, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/lib/python3.10/shutil.py", line 198, in copyfileobj
    fdst_write(buf)
  File "/usr/lib/python3.10/socketserver.py", line 826, in write
    self._sock.sendall(b)
----------------------------------------
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
Exception in thread Thread-9 (inference_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/draw2img/server/main.py", line 94, in inference_loop
    output = img2img_inference(payload, params)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/draw2img/server/main.py", line 49, in img2img_inference
    r = pipe(
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 1281, in __call__
    latents = self.prepare_latents(
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 721, in prepare_latents
    init_latents = retrieve_latents(self.vae.encode(image), generator=generator)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 261, in encode
    h = self.encoder(x)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/models/autoencoders/vae.py", line 172, in forward
    sample = down_block(sample)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1474, in forward
    hidden_states = resnet(hidden_states, temb=None)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/models/resnet.py", line 371, in forward
    output_tensor = (input_tensor + hidden_states) / self.output_scale_factor
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB. GPU 0 has a total capacity of 7.92 GiB of which 113.00 MiB is free. Including non-PyTorch memory, this process has 7.49 GiB memory in use. Of the allocated memory 7.11 GiB is allocated by PyTorch, and 257.90 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
python3.10 draw2img/main.py127.0.0.1 - - [04/Aug/2024 21:50:50] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [04/Aug/2024 21:50:50] "GET /assets/index-AQAbczng.js HTTP/1.1" 304 -
127.0.0.1 - - [04/Aug/2024 21:50:50] "GET /assets/index-6cmW4xtb.css HTTP/1.1" 304 -
Exception in thread Thread-17 (inference_loop):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/draw2img/server/main.py", line 94, in inference_loop
    output = img2img_inference(payload, params)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/draw2img/server/main.py", line 49, in img2img_inference
    r = pipe(
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 1281, in __call__
    latents = self.prepare_latents(
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/pipelines/stable_diffusion_xl/pipeline_stable_diffusion_xl_img2img.py", line 721, in prepare_latents
    init_latents = retrieve_latents(self.vae.encode(image), generator=generator)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/utils/accelerate_utils.py", line 46, in wrapper
    return method(self, *args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/models/autoencoders/autoencoder_kl.py", line 261, in encode
    h = self.encoder(x)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/models/autoencoders/vae.py", line 172, in forward
    sample = down_block(sample)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 1474, in forward
    hidden_states = resnet(hidden_states, temb=None)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Morselius/disks/ssh/my-venv/lib/python3.10/site-packages/diffusers/models/resnet.py", line 371, in forward
    output_tensor = (input_tensor + hidden_states) / self.output_scale_factor
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 128.00 MiB. GPU 0 has a total capacity of 7.92 GiB of which 27.38 MiB is free. Including non-PyTorch memory, this process has 7.49 GiB memory in use. Of the allocated memory 7.11 GiB is allocated by PyTorch, and 257.90 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

**Comment by GradientSurfer** [comment]
Hi @RazerStvH thanks for the details, unfortunately based on the logs it seems your GPU has 8 GB of memory which is likely not enough to run the SDXL-Turbo model. You could try using a tool like [NVTOP](https://github.com/Syllo/nvtop) to see if any other processes are using a lot of GPU memory, closing those processes may free up enough memory for it to work but I can't be sure. The only other workaround I can think of is to run it on the CPU instead, but of course that will be much slower and less interactive.

**Comment by RazerStvH** [comment]
Yep, i have only 8 GB VRAM. And the model uses it all.

But i thought that would be enough because you wrote: "GPU with at least 10 GB VRAM is recommended, but not strictly required" in your requirements.

Thanks for answer.
