### ISSUE TITLE
`ModuleNotFoundError: No module named 'torch'`

### ISSUE THREAD

**Issue by vergenzt** [GradientSurfer/Draw2Img#5]
Seems like a declared dependency is missing? 🤔 Looks like a really neat project!

```
Draw2Img on ⤴ main (4df6dad) is 📦 v0.0.1 via 🐍 v3.10.2 on ☁️
14:35:03 $ virtualenv .venv
created virtual environment CPython3.12.0.final.0-64 in 619ms
  creator CPython3macOsBrew(dest=/Users/tim_vergenz/code/Draw2Img/.venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/Users/tim_vergenz/Library/Application Support/virtualenv)
    added seed packages: pip==23.3.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

Draw2Img on ⤴ main (4df6dad) is 📦 v0.0.1 via 🐍 v3.10.2 on ☁️   took 3s
14:35:14 $ source .venv/bin/activate.fish

Draw2Img on ⤴ main (4df6dad) is 📦 v0.0.1 via 🐍 v3.12.0 (.venv) on ☁️
14:35:17 $

Draw2Img on ⤴ main (4df6dad) is 📦 v0.0.1 via 🐍 v3.12.0 (.venv) on ☁️
14:35:18 $ pip install .
Processing /Users/tim_vergenz/code/Draw2Img
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting accelerate (from draw2img==0.0.1)
  Downloading accelerate-0.26.1-py3-none-any.whl.metadata (18 kB)
Collecting diffusers (from draw2img==0.0.1)
  Downloading diffusers-0.25.0-py3-none-any.whl.metadata (19 kB)
Collecting fire (from draw2img==0.0.1)
  Downloading fire-0.5.0.tar.gz (88 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.3/88.3 kB 2.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from draw2img==0.0.1)
  Downloading numpy-1.26.3-cp312-cp312-macosx_10_9_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.2/61.2 kB 4.6 MB/s eta 0:00:00
Collecting pillow (from draw2img==0.0.1)
  Downloading pillow-10.2.0-cp312-cp312-macosx_10_10_x86_64.whl.metadata (9.7 kB)
Collecting pydantic (from draw2img==0.0.1)
  Downloading pydantic-2.5.3-py3-none-any.whl.metadata (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.6/65.6 kB 6.6 MB/s eta 0:00:00
Collecting safetensors (from draw2img==0.0.1)
  Downloading safetensors-0.4.1-cp312-cp312-macosx_10_7_x86_64.whl.metadata (3.8 kB)
Collecting transformers (from draw2img==0.0.1)
  Downloading transformers-4.36.2-py3-none-any.whl.metadata (126 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.8/126.8 kB 8.3 MB/s eta 0:00:00
Collecting websockets (from draw2img==0.0.1)
  Downloading websockets-12.0-cp312-cp312-macosx_10_9_x86_64.whl.metadata (6.6 kB)
Collecting packaging>=20.0 (from accelerate->draw2img==0.0.1)
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting psutil (from accelerate->draw2img==0.0.1)
  Downloading psutil-5.9.7-cp36-abi3-macosx_10_9_x86_64.whl.metadata (21 kB)
Collecting pyyaml (from accelerate->draw2img==0.0.1)
  Using cached PyYAML-6.0.1-cp312-cp312-macosx_10_9_x86_64.whl.metadata (2.1 kB)
INFO: pip is looking at multiple versions of accelerate to determine which version is compatible with other requirements. This could take a while.
Collecting accelerate (from draw2img==0.0.1)
  Downloading accelerate-0.26.0-py3-none-any.whl.metadata (18 kB)
  Downloading accelerate-0.25.0-py3-none-any.whl.metadata (18 kB)
  Downloading accelerate-0.24.1-py3-none-any.whl.metadata (18 kB)
  Downloading accelerate-0.24.0-py3-none-any.whl.metadata (18 kB)
  Downloading accelerate-0.23.0-py3-none-any.whl.metadata (18 kB)
  Downloading accelerate-0.22.0-py3-none-any.whl.metadata (17 kB)
  Downloading accelerate-0.21.0-py3-none-any.whl.metadata (17 kB)
INFO: pip is still looking at multiple versions of accelerate to determine which version is compatible with other requirements. This could take a while.
  Downloading accelerate-0.20.3-py3-none-any.whl.metadata (17 kB)
  Downloading accelerate-0.20.2-py3-none-any.whl.metadata (17 kB)
  Downloading accelerate-0.20.1-py3-none-any.whl.metadata (17 kB)
  Downloading accelerate-0.20.0-py3-none-any.whl.metadata (17 kB)
  Downloading accelerate-0.19.0-py3-none-any.whl (219 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 219.1/219.1 kB 11.1 MB/s eta 0:00:00
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading accelerate-0.18.0-py3-none-any.whl (215 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 215.3/215.3 kB 11.3 MB/s eta 0:00:00
  Downloading accelerate-0.17.1-py3-none-any.whl (212 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.8/212.8 kB 12.6 MB/s eta 0:00:00
  Downloading accelerate-0.17.0-py3-none-any.whl (212 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.8/212.8 kB 9.7 MB/s eta 0:00:00
  Downloading accelerate-0.16.0-py3-none-any.whl (199 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.7/199.7 kB 10.7 MB/s eta 0:00:00
  Downloading accelerate-0.15.0-py3-none-any.whl (191 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 191.5/191.5 kB 11.6 MB/s eta 0:00:00
  Downloading accelerate-0.14.0-py3-none-any.whl (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.0/176.0 kB 11.8 MB/s eta 0:00:00
  Downloading accelerate-0.13.2-py3-none-any.whl (148 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.8/148.8 kB 9.9 MB/s eta 0:00:00
  Downloading accelerate-0.13.1-py3-none-any.whl (148 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.8/148.8 kB 10.4 MB/s eta 0:00:00
  Downloading accelerate-0.13.0-py3-none-any.whl (148 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.8/148.8 kB 9.6 MB/s eta 0:00:00
  Downloading accelerate-0.12.0-py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.0/144.0 kB 9.5 MB/s eta 0:00:00
  Downloading accelerate-0.11.0-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.1/123.1 kB 10.5 MB/s eta 0:00:00
  Downloading accelerate-0.10.0-py3-none-any.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.1/117.1 kB 7.4 MB/s eta 0:00:00
  Downloading accelerate-0.9.0-py3-none-any.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 7.1 MB/s eta 0:00:00
  Downloading accelerate-0.8.0-py3-none-any.whl (114 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 8.1 MB/s eta 0:00:00
  Downloading accelerate-0.7.1-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 kB 7.8 MB/s eta 0:00:00
  Downloading accelerate-0.7.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 kB 7.9 MB/s eta 0:00:00
  Downloading accelerate-0.6.2-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.9/65.9 kB 4.4 MB/s eta 0:00:00
  Downloading accelerate-0.6.1-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.9/65.9 kB 6.3 MB/s eta 0:00:00
  Downloading accelerate-0.6.0-py3-none-any.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.8/65.8 kB 4.1 MB/s eta 0:00:00
  Downloading accelerate-0.5.1-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.0/58.0 kB 4.5 MB/s eta 0:00:00
  Downloading accelerate-0.5.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.0/58.0 kB 6.8 MB/s eta 0:00:00
  Downloading accelerate-0.4.0-py3-none-any.whl (55 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 kB 6.1 MB/s eta 0:00:00
  Downloading accelerate-0.3.0-py3-none-any.whl (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.0/50.0 kB 5.3 MB/s eta 0:00:00
  Downloading accelerate-0.2.1-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 kB 3.7 MB/s eta 0:00:00
  Downloading accelerate-0.2.0-py3-none-any.whl (47 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.3/47.3 kB 3.1 MB/s eta 0:00:00
  Downloading accelerate-0.1.0-py3-none-any.whl (34 kB)
  Downloading accelerate-0.0.1-py3-none-any.whl (5.7 kB)
Collecting importlib-metadata (from diffusers->draw2img==0.0.1)
  Downloading importlib_metadata-7.0.1-py3-none-any.whl.metadata (4.9 kB)
Collecting filelock (from diffusers->draw2img==0.0.1)
  Using cached filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
Collecting huggingface-hub>=0.19.4 (from diffusers->draw2img==0.0.1)
  Downloading huggingface_hub-0.20.2-py3-none-any.whl.metadata (12 kB)
Collecting regex!=2019.12.17 (from diffusers->draw2img==0.0.1)
  Downloading regex-2023.12.25-cp312-cp312-macosx_10_9_x86_64.whl.metadata (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 kB 3.2 MB/s eta 0:00:00
Collecting requests (from diffusers->draw2img==0.0.1)
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting six (from fire->draw2img==0.0.1)
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting termcolor (from fire->draw2img==0.0.1)
  Downloading termcolor-2.4.0-py3-none-any.whl.metadata (6.1 kB)
Collecting annotated-types>=0.4.0 (from pydantic->draw2img==0.0.1)
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.14.6 (from pydantic->draw2img==0.0.1)
  Downloading pydantic_core-2.14.6-cp312-cp312-macosx_10_7_x86_64.whl.metadata (6.5 kB)
Collecting typing-extensions>=4.6.1 (from pydantic->draw2img==0.0.1)
  Downloading typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting tokenizers<0.19,>=0.14 (from transformers->draw2img==0.0.1)
  Downloading tokenizers-0.15.0-cp312-cp312-macosx_10_7_x86_64.whl.metadata (6.7 kB)
Collecting tqdm>=4.27 (from transformers->draw2img==0.0.1)
  Downloading tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 5.2 MB/s eta 0:00:00
Collecting fsspec>=2023.5.0 (from huggingface-hub>=0.19.4->diffusers->draw2img==0.0.1)
  Downloading fsspec-2023.12.2-py3-none-any.whl.metadata (6.8 kB)
Collecting zipp>=0.5 (from importlib-metadata->diffusers->draw2img==0.0.1)
  Downloading zipp-3.17.0-py3-none-any.whl.metadata (3.7 kB)
Collecting charset-normalizer<4,>=2 (from requests->diffusers->draw2img==0.0.1)
  Downloading charset_normalizer-3.3.2-cp312-cp312-macosx_10_9_x86_64.whl.metadata (33 kB)
Collecting idna<4,>=2.5 (from requests->diffusers->draw2img==0.0.1)
  Downloading idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests->diffusers->draw2img==0.0.1)
  Downloading urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests->diffusers->draw2img==0.0.1)
  Downloading certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Downloading diffusers-0.25.0-py3-none-any.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 12.5 MB/s eta 0:00:00
Downloading safetensors-0.4.1-cp312-cp312-macosx_10_7_x86_64.whl (440 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.8/440.8 kB 10.1 MB/s eta 0:00:00
Downloading numpy-1.26.3-cp312-cp312-macosx_10_9_x86_64.whl (20.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.3/20.3 MB 13.2 MB/s eta 0:00:00
Downloading pillow-10.2.0-cp312-cp312-macosx_10_10_x86_64.whl (3.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 13.9 MB/s eta 0:00:00
Downloading pydantic-2.5.3-py3-none-any.whl (381 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 381.9/381.9 kB 8.2 MB/s eta 0:00:00
Downloading pydantic_core-2.14.6-cp312-cp312-macosx_10_7_x86_64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 13.7 MB/s eta 0:00:00
Downloading transformers-4.36.2-py3-none-any.whl (8.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 14.1 MB/s eta 0:00:00
Downloading websockets-12.0-cp312-cp312-macosx_10_9_x86_64.whl (121 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.3/121.3 kB 4.2 MB/s eta 0:00:00
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Downloading huggingface_hub-0.20.2-py3-none-any.whl (330 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 330.3/330.3 kB 14.1 MB/s eta 0:00:00
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached PyYAML-6.0.1-cp312-cp312-macosx_10_9_x86_64.whl (178 kB)
Downloading regex-2023.12.25-cp312-cp312-macosx_10_9_x86_64.whl (298 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.1/298.1 kB 10.2 MB/s eta 0:00:00
Downloading tokenizers-0.15.0-cp312-cp312-macosx_10_7_x86_64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 14.0 MB/s eta 0:00:00
Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 4.5 MB/s eta 0:00:00
Downloading typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Downloading importlib_metadata-7.0.1-py3-none-any.whl (23 kB)
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 6.0 MB/s eta 0:00:00
Downloading termcolor-2.4.0-py3-none-any.whl (7.7 kB)
Downloading certifi-2023.11.17-py3-none-any.whl (162 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 kB 10.1 MB/s eta 0:00:00
Downloading charset_normalizer-3.3.2-cp312-cp312-macosx_10_9_x86_64.whl (122 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.2/122.2 kB 6.7 MB/s eta 0:00:00
Downloading fsspec-2023.12.2-py3-none-any.whl (168 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 169.0/169.0 kB 10.7 MB/s eta 0:00:00
Downloading idna-3.6-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.6/61.6 kB 4.4 MB/s eta 0:00:00
Downloading urllib3-2.1.0-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.6/104.6 kB 7.5 MB/s eta 0:00:00
Downloading zipp-3.17.0-py3-none-any.whl (7.4 kB)
Building wheels for collected packages: draw2img, fire
  Building wheel for draw2img (pyproject.toml) ... done
  Created wheel for draw2img: filename=draw2img-0.0.1-py3-none-any.whl size=117981 sha256=fdcf88364bba8fd2d83d3f5f43cca7625b16d600315ec7027dabe29e96749490
  Stored in directory: /private/var/folders/dp/h28mjqfd1yq_28qc0gj_vzkw0000gn/T/pip-ephem-wheel-cache-o6rxzl9n/wheels/ce/fa/38/1e08167766c8d23dcd6bb6208239182274ac130325228dda21
  Building wheel for fire (pyproject.toml) ... done
  Created wheel for fire: filename=fire-0.5.0-py2.py3-none-any.whl size=116934 sha256=43204a5a94ada3c63b82b60c1fff7773eac2d56164de19663b74b992421edcfa
  Stored in directory: /Users/tim_vergenz/Library/Caches/pip/wheels/ef/b7/5a/429bf9270449b3fbca3c36b235c97f5ad1585f95cd8d9bb1ab
Successfully built draw2img fire
Installing collected packages: zipp, websockets, urllib3, typing-extensions, tqdm, termcolor, six, safetensors, regex, pyyaml, pillow, packaging, numpy, idna, fsspec, filelock, charset-normalizer, certifi, annotated-types, accelerate, requests, pydantic-core, importlib-metadata, fire, pydantic, huggingface-hub, tokenizers, diffusers, transformers, draw2img
Successfully installed accelerate-0.0.1 annotated-types-0.6.0 certifi-2023.11.17 charset-normalizer-3.3.2 diffusers-0.25.0 draw2img-0.0.1 filelock-3.13.1 fire-0.5.0 fsspec-2023.12.2 huggingface-hub-0.20.2 idna-3.6 importlib-metadata-7.0.1 numpy-1.26.3 packaging-23.2 pillow-10.2.0 pydantic-2.5.3 pydantic-core-2.14.6 pyyaml-6.0.1 regex-2023.12.25 requests-2.31.0 safetensors-0.4.1 six-1.16.0 termcolor-2.4.0 tokenizers-0.15.0 tqdm-4.66.1 transformers-4.36.2 typing-extensions-4.9.0 urllib3-2.1.0 websockets-12.0 zipp-3.17.0

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip

Draw2Img on ⤴ main (4df6dad) is 📦 v0.0.1 via 🐍 v3.12.0 (.venv) on ☁️   took 26s
14:35:51 $ python draw2img/main.py
Traceback (most recent call last):
  File "/Users/tim_vergenz/code/Draw2Img/draw2img/main.py", line 11, in <module>
    from draw2img.server import server
  File "/Users/tim_vergenz/code/Draw2Img/.venv/lib/python3.12/site-packages/draw2img/__init__.py", line 1, in <module>
    from .main import main
  File "/Users/tim_vergenz/code/Draw2Img/.venv/lib/python3.12/site-packages/draw2img/main.py", line 11, in <module>
    from draw2img.server import server
  File "/Users/tim_vergenz/code/Draw2Img/.venv/lib/python3.12/site-packages/draw2img/server/__init__.py", line 1, in <module>
    from .main import server
  File "/Users/tim_vergenz/code/Draw2Img/.venv/lib/python3.12/site-packages/draw2img/server/main.py", line 9, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

**Comment by GradientSurfer** [comment]
Hi @vergenzt thank you for the kind words and the report! Am I seeing correctly that Python 3.12 was used? If so I suspect that may be the culprit, the dependencies used in this project don't seem to support it yet (it was only released ~3 months ago). Could you please try Python 3.11 instead?

Edit: I was able to reproduce this on Linux, pytorch doesn't support Python 3.12 yet https://github.com/pytorch/pytorch/issues/110436 .

I've updated this package to require Python < 3.12 so a clear error message is shown during the `pip install .`
