### ISSUE TITLE
ModuleNotFoundError: No module named 'websockets.sync'

### ISSUE THREAD

**Issue by vpreparate** [GradientSurfer/Draw2Img#6]
The `websockets` module is already installed. The error appears to be due to the fact that the synchronous version of `websockets` is being used while the code is trying to import the `websockets.sync` module.

Traceback (most recent call last):
  File "D:\AI\Draw2Img\Draw2Img-main\draw2img\main.py", line 11, in <module>
    from draw2img.server import server
  File "C:\Python\lib\site-packages\draw2img\__init__.py", line 1, in <module>
    from .main import main
  File "C:\Python\lib\site-packages\draw2img\main.py", line 11, in <module>
    from draw2img.server import server
  File "C:\Python\lib\site-packages\draw2img\server\__init__.py", line 1, in <module>
    from .main import server
  File "C:\Python\lib\site-packages\draw2img\server\main.py", line 13, in <module>
    from websockets.sync.server import WebSocketServer, serve
ModuleNotFoundError: No module named 'websockets.sync'

**Comment by GradientSurfer** [comment]
Hi @vpreparate thanks for the report, unfortunately I have not been able to reproduce this error on Linux after a fresh install (`python -m websockets --version` shows `12.0` which is the latest release).

Can you confirm what version of `websockets` you have installed?

**Comment by vpreparate** [comment]
ok download model start!!!
