### ISSUE TITLE
The interface started but the model draws once in a strange way, then refuses to draw

### ISSUE THREAD

**Issue by vpreparate** [GradientSurfer/Draw2Img#8]
127.0.0.1 - - [09/Apr/2024 10:45:18] "GET / HTTP/1.1" 304 -
127.0.0.1 - - [09/Apr/2024 10:45:19] code 404, message File not found
127.0.0.1 - - [09/Apr/2024 10:45:19] "GET /site.webmanifest HTTP/1.1" 404 -
Exception in thread Thread-8 (inference_loop):
Traceback (most recent call last):
  File "C:\Python\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\lib\site-packages\draw2img\server\main.py", line 86, in inference_loop
    params = Params.model_validate(obj)
AttributeError: type object 'Params' has no attribute 'model_validate'

![1](https://github.com/GradientSurfer/Draw2Img/assets/90881743/2de63dab-46a3-4b7b-81ab-816acc9ad103)
![2024-04-09T07_49_22 171Z_output](https://github.com/GradientSurfer/Draw2Img/assets/90881743/1ac994ea-b1a0-41cf-a8b3-a3493100a4c9)
![2](https://github.com/GradientSurfer/Draw2Img/assets/90881743/47d080ae-2528-4716-b203-c5f77028222f)

**Comment by GradientSurfer** [comment]
Hi @vpreparate, could you please share your Python version (`python --version`), operating system version (eg Linux 6.1), and pydantic version (`python -c "import pydantic; print(pydantic.version.version_info())"`)?

**Comment by vpreparate** [comment]
Python 3.10.5 Windows 10  pydantic version: 1.8.2
            pydantic compiled: False

**Comment by Ichigo3766** [comment]
Hey! Just tried this myself and seeing the same issue. Its only the drawing. If you write the prompt that seems to work fine and updating realtime but drawing wont update realtime.

**Comment by RioSamson** [comment]
I am having the same problem. There is no realtime update. Also when I give it a different word prompt like "police" and draw a stick figure, it still makes a picture of the ocean

**Comment by GradientSurfer** [comment]
@vpreparate Thank you, I believe the issue is caused due to the old version of pydantic (1.8.2 was released May 2021). For some reason I was not able to reproduce the exception in your screenshot even when using pydantic 1.8.2. However I've found reports of similar issues in other projects (eg see https://github.com/chroma-core/chroma/issues/2137).

To remedy this I've pinned the dependencies in this project to recent versions that are known to work. Please try to pull/download the latest version (v0.0.4) and reinstall dependencies via `pip install .`  

@Ichigo3766  @RioSamson Thank you for your reports, I am hopeful this will also resolve the issues you are facing. If it does not, please feel free to share more details about your hardware and software versions so we may have a chance to identify any commonalities.
